# -*- coding: utf-8 -*-
"""Ramco.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_2f3RSzLkJvsx3lajcYnNN--wYx7Wp8v
"""

import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("tasks.csv")

df.head(20)



plt.bar(df['Mem Usage'],df['Image Name'], align='center', alpha=0.5,color='g')
plt.show()

df.shape

plt.bar(df['Session Name'],df['Mem Usage'], align='center', alpha=0.5)
plt.show()

df['Image Name'].unique()



